# start numbering at 1 instead of 0, because 0 is far away to the right on the keyboard
set -g base-index 1
setw -g pane-base-index 1

# remap prefix to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# tmux nvim
set-option -sg escape-time 10
set-option -g focus-events on 
set-option -sa terminal-features ',xterm-256color:RGB'
